"""PR operations with GitHub and local patch fallback."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil
import subprocess


@dataclass(frozen=True)
class PRResult:
    mode: str
    success: bool
    message: str
    artifact_path: Path | None


def _has_github_capability() -> bool:
    if shutil.which("gh") is None:
        return False
    return bool(shutil.which("git"))


def create_pr_or_fallback(
    repo_path: Path,
    branch_name: str,
    task_title: str,
    run_dir: Path,
    pr_mode: str,
) -> PRResult:
    if pr_mode == "github" and _has_github_capability():
        title = f"[autodev] {task_title}"
        body = (
            "## Summary\n"
            "- Automated incremental change generated by autodev.\n"
            "- All configured gates passed in run report artifacts.\n\n"
            "## Safety\n"
            "- No direct main/master commits.\n"
            "- Branch: " + branch_name + "\n"
        )
        cmd = ["gh", "pr", "create", "--title", title, "--body", body]
        proc = subprocess.run(
            cmd,
            cwd=repo_path,
            text=True,
            capture_output=True,
            check=False,
        )
        if proc.returncode == 0:
            return PRResult(
                mode="github",
                success=True,
                message=proc.stdout.strip() or "PR created successfully.",
                artifact_path=None,
            )
        # fall through to local patch if gh call fails.

    patch_path = run_dir / "pr_patch.diff"
    instructions_path = run_dir / "PR_INSTRUCTIONS.md"
    subprocess.run(
        ["git", "diff"],
        cwd=repo_path,
        text=True,
        capture_output=False,
        check=False,
        stdout=patch_path.open("w", encoding="utf-8"),
    )
    instructions_path.write_text(
        "\n".join(
            [
                "# Local PR Instructions",
                "",
                f"- Branch: `{branch_name}`",
                f"- Task: `{task_title}`",
                "- A local patch has been generated at `pr_patch.diff`.",
                "- Review changes, commit on the agent branch, then open a PR manually.",
                "- Auto-merge remains disabled unless explicitly enabled by a human.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return PRResult(
        mode="local_patch",
        success=True,
        message="Generated local patch and PR instructions.",
        artifact_path=instructions_path,
    )

