"""Tests for market_update_reports + market_update_followups persistence.

P2 of the cockpit verbal market updates plus holdings v1.

These tables hold cockpit-local report snapshots and queued follow-up actions
generated by the noon-preview / final-report orchestrator (P5). Per
SYSTEM_CONTRACT §1.2 they are client-side state only, not financial truth.
"""
from __future__ import annotations

import time
from pathlib import Path

import pytest

from cockpit.storage.state import StateStore


@pytest.fixture()
def store(tmp_path: Path) -> StateStore:
    return StateStore(str(tmp_path / "state.db"))


# ---------------------------------------------------------------------------
# market_update_reports — save / get_latest / list
# ---------------------------------------------------------------------------


def test_save_market_update_report_persists_and_returns_id(store: StateStore) -> None:
    summary = {
        "winners": [{"ticker": "BHP", "pct": 4.2}],
        "losers": [{"ticker": "CBA", "pct": -1.1}],
        "holdings_impact": [],
    }
    report_id = store.save_market_update_report(
        run_type="noon",
        report_date="2026-04-20",
        status="ok",
        summary=summary,
    )
    assert isinstance(report_id, str) and report_id

    fetched = store.get_latest_market_update_report()
    assert fetched is not None
    assert fetched["report_id"] == report_id
    assert fetched["run_type"] == "noon"
    assert fetched["report_date"] == "2026-04-20"
    assert fetched["status"] == "ok"
    assert fetched["summary"] == summary  # round-trips as dict
    assert fetched["created_at"]


def test_save_market_update_report_accepts_all_run_types(store: StateStore) -> None:
    for run_type in ("noon", "final", "manual"):
        store.save_market_update_report(
            run_type=run_type,
            report_date="2026-04-20",
            status="ok",
            summary={"run_type_check": run_type},
        )
    rows = store.list_market_update_reports()
    types = sorted(r["run_type"] for r in rows)
    assert types == ["final", "manual", "noon"]


def test_save_market_update_report_rejects_invalid_run_type(store: StateStore) -> None:
    """The CHECK constraint must guard the noon/final/manual contract."""
    import sqlite3
    with pytest.raises(sqlite3.IntegrityError):
        store.save_market_update_report(
            run_type="weekly",  # not allowed
            report_date="2026-04-20",
            status="ok",
            summary={},
        )


def test_save_market_update_report_with_paths(store: StateStore) -> None:
    report_id = store.save_market_update_report(
        run_type="final",
        report_date="2026-04-20",
        status="ok",
        summary={"sections": ["winners"]},
        markdown_path="/tmp/report.md",
        json_path="/tmp/report.json",
    )
    fetched = store.get_latest_market_update_report()
    assert fetched is not None
    assert fetched["report_id"] == report_id
    assert fetched["markdown_path"] == "/tmp/report.md"
    assert fetched["json_path"] == "/tmp/report.json"


def test_save_market_update_report_paths_default_to_none(store: StateStore) -> None:
    store.save_market_update_report(
        run_type="noon",
        report_date="2026-04-20",
        status="ok",
        summary={},
    )
    fetched = store.get_latest_market_update_report()
    assert fetched is not None
    assert fetched["markdown_path"] is None
    assert fetched["json_path"] is None


def test_get_latest_market_update_report_returns_none_when_empty(
    store: StateStore,
) -> None:
    assert store.get_latest_market_update_report() is None
    assert store.get_latest_market_update_report(run_type="noon") is None


def test_get_latest_market_update_report_filtered_by_run_type(
    store: StateStore,
) -> None:
    store.save_market_update_report(
        run_type="noon", report_date="2026-04-20", status="ok", summary={"v": 1}
    )
    time.sleep(0.01)
    store.save_market_update_report(
        run_type="final", report_date="2026-04-20", status="ok", summary={"v": 2}
    )
    time.sleep(0.01)
    store.save_market_update_report(
        run_type="noon", report_date="2026-04-20", status="ok", summary={"v": 3}
    )

    latest_any = store.get_latest_market_update_report()
    assert latest_any is not None
    assert latest_any["summary"] == {"v": 3}

    latest_final = store.get_latest_market_update_report(run_type="final")
    assert latest_final is not None
    assert latest_final["summary"] == {"v": 2}

    latest_noon = store.get_latest_market_update_report(run_type="noon")
    assert latest_noon is not None
    assert latest_noon["summary"] == {"v": 3}


def test_list_market_update_reports_orders_newest_first_with_limit(
    store: StateStore,
) -> None:
    for i in range(5):
        store.save_market_update_report(
            run_type="noon",
            report_date="2026-04-20",
            status="ok",
            summary={"i": i},
        )
        time.sleep(0.005)

    rows = store.list_market_update_reports(limit=3)
    assert len(rows) == 3
    indices = [r["summary"]["i"] for r in rows]
    assert indices == [4, 3, 2]


def test_list_market_update_reports_filtered_by_run_type(store: StateStore) -> None:
    store.save_market_update_report(
        run_type="noon", report_date="2026-04-20", status="ok", summary={"a": 1}
    )
    store.save_market_update_report(
        run_type="final", report_date="2026-04-20", status="ok", summary={"b": 2}
    )
    store.save_market_update_report(
        run_type="noon", report_date="2026-04-21", status="ok", summary={"c": 3}
    )

    noon_rows = store.list_market_update_reports(run_type="noon")
    assert len(noon_rows) == 2
    final_rows = store.list_market_update_reports(run_type="final")
    assert len(final_rows) == 1


def test_list_market_update_reports_filtered_by_report_date(store: StateStore) -> None:
    store.save_market_update_report(
        run_type="noon", report_date="2026-04-19", status="ok", summary={}
    )
    store.save_market_update_report(
        run_type="final", report_date="2026-04-20", status="ok", summary={}
    )
    store.save_market_update_report(
        run_type="noon", report_date="2026-04-20", status="ok", summary={}
    )

    apr20 = store.list_market_update_reports(report_date="2026-04-20")
    assert len(apr20) == 2
    apr19 = store.list_market_update_reports(report_date="2026-04-19")
    assert len(apr19) == 1


# ---------------------------------------------------------------------------
# market_update_followups
# ---------------------------------------------------------------------------


@pytest.fixture()
def report_id(store: StateStore) -> str:
    """A report row to attach followups to."""
    return store.save_market_update_report(
        run_type="final",
        report_date="2026-04-20",
        status="ok",
        summary={},
    )


def test_add_market_update_followup_persists(
    store: StateStore, report_id: str
) -> None:
    reason = {
        "score": 0.82,
        "components": {"holdings_match": 1.0, "abnormal_move": 0.5},
        "sources": ["asx_announcement:CBA-2026-04-20"],
    }
    followup_id = store.add_market_update_followup(
        report_id=report_id,
        ticker="cba",
        action_type="watchlist_add_proposal",
        priority_score=0.82,
        reason=reason,
    )
    assert isinstance(followup_id, str) and followup_id

    rows = store.list_market_update_followups(report_id=report_id)
    assert len(rows) == 1
    row = rows[0]
    assert row["followup_id"] == followup_id
    assert row["ticker"] == "CBA"  # normalised
    assert row["action_type"] == "watchlist_add_proposal"
    assert row["priority_score"] == 0.82
    assert row["status"] == "queued"  # default
    assert row["reason"] == reason  # round-trips as dict
    assert row["created_at"]


def test_add_market_update_followup_priority_defaults_to_zero(
    store: StateStore, report_id: str
) -> None:
    followup_id = store.add_market_update_followup(
        report_id=report_id,
        action_type="research_queue",
        reason={"note": "investigate"},
    )
    rows = store.list_market_update_followups(report_id=report_id)
    assert len(rows) == 1
    assert rows[0]["followup_id"] == followup_id
    assert rows[0]["priority_score"] == 0.0
    assert rows[0]["ticker"] is None  # ticker is optional


def test_list_market_update_followups_orders_by_priority_desc(
    store: StateStore, report_id: str
) -> None:
    store.add_market_update_followup(
        report_id=report_id,
        ticker="LOW",
        action_type="research_queue",
        priority_score=0.1,
        reason={},
    )
    store.add_market_update_followup(
        report_id=report_id,
        ticker="HIGH",
        action_type="research_queue",
        priority_score=0.9,
        reason={},
    )
    store.add_market_update_followup(
        report_id=report_id,
        ticker="MID",
        action_type="research_queue",
        priority_score=0.5,
        reason={},
    )

    rows = store.list_market_update_followups(report_id=report_id)
    assert [r["ticker"] for r in rows] == ["HIGH", "MID", "LOW"]


def test_list_market_update_followups_filter_by_status(
    store: StateStore, report_id: str
) -> None:
    f1 = store.add_market_update_followup(
        report_id=report_id, action_type="research_queue", reason={}
    )
    f2 = store.add_market_update_followup(
        report_id=report_id, action_type="research_queue", reason={}
    )
    store.update_market_update_followup_status(f1, "accepted")

    queued = store.list_market_update_followups(report_id=report_id, status="queued")
    assert len(queued) == 1
    assert queued[0]["followup_id"] == f2

    accepted = store.list_market_update_followups(
        report_id=report_id, status="accepted"
    )
    assert len(accepted) == 1
    assert accepted[0]["followup_id"] == f1


def test_list_market_update_followups_can_query_across_reports(
    store: StateStore,
) -> None:
    r1 = store.save_market_update_report(
        run_type="noon", report_date="2026-04-20", status="ok", summary={}
    )
    r2 = store.save_market_update_report(
        run_type="final", report_date="2026-04-20", status="ok", summary={}
    )
    store.add_market_update_followup(
        report_id=r1, action_type="research_queue", reason={}
    )
    store.add_market_update_followup(
        report_id=r2, action_type="research_queue", reason={}
    )
    store.add_market_update_followup(
        report_id=r2, action_type="watchlist_add_proposal", reason={}
    )

    all_rows = store.list_market_update_followups()  # no report_id filter
    assert len(all_rows) == 3

    r2_rows = store.list_market_update_followups(report_id=r2)
    assert len(r2_rows) == 2


def test_update_market_update_followup_status_changes_status(
    store: StateStore, report_id: str
) -> None:
    followup_id = store.add_market_update_followup(
        report_id=report_id, action_type="watchlist_add_proposal", reason={}
    )
    assert store.update_market_update_followup_status(followup_id, "accepted") is True

    rows = store.list_market_update_followups(report_id=report_id)
    assert rows[0]["status"] == "accepted"


def test_update_market_update_followup_status_returns_false_when_missing(
    store: StateStore,
) -> None:
    assert (
        store.update_market_update_followup_status("does-not-exist", "accepted")
        is False
    )
